/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./src/components/AppHeader copy 2.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppFooter1: typeof import('./src/components/AppFooter.vue')['default']
    AppFooter2: typeof import('./src/components/AppFooter2.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppHeader12: typeof import('./src/components/AppHeader12.vue')['default']
    AppHeaderV02: typeof import('./src/components/AppHeaderV02.vue')['default']
    Carousel: typeof import('./src/components/carousel.vue')['default']
    copy: typeof import('./src/components/UserStatusDialog copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserStatusDialog: typeof import('./src/components/UserStatusDialog.vue')['default']
  }
}
